[package]
name = "leth"
version = "0.3.0"
authors = ["fcd <femnad@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
skim = "0.7.0"
structopt = "0.3.26"
