on: push

name: Tag version

jobs:
  build:
    name: Tag version if tag untaken
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Tag version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email autotag
          git config user.name autotag
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          version=$(grep -E 'version = "[0-9.]+"' Cargo.toml | awk -F '"' '{print $2}')
          if ! git tag | grep "$version"
          then
              git tag "$version"
              git push --tags
          fi
